#!/bin/zsh

gcc -o 1 -D TESTMODE 1.c

for i in {1..256} ; do
    for j in {1..256} ; do
        s1=$(cat /dev/urandom | tr -cd "[:digit:]" | head --bytes=$i)
        s2=$(cat /dev/urandom | tr -cd "[:digit:]" | head --bytes=$j)
        (echo $s1 ; echo $s2) | ./1
    done
done
