#!/bin/zsh

(repeat $(expr $1 / $2 + 1) (repeat $2 echo -n '0') | sed "s/.$/1/g") | head -c $1 | sed "s/.$/1/g"
echo -n ' '
repeat $2 echo -n '0'
echo

#(repeat $1 echo -n '0') | sed "s/.$/1/"
#echo -n ' '
#(repeat $2 echo -n '0') | sed "s/.$/2/"
#echo
