#!/bin/zsh

gcc -o 1-2 1-2.c
gcc -o 2-2 2-2.c

xrange="0,511"

function genrange(){
    echo {$(echo $1 | sed "s/,.*//")..$(echo $1 | sed "s/.*,//")}
}

function genrange-gp(){
    echo -n [
    echo -n $1 | sed "s/,/:/"
    echo ]
}

for i in $(genrange $xrange) ; do
    input=$(cat /dev/urandom | tr -cd "[:digit:]" | fold -w 5 | head -n $i)
    echo $i $input | ./1-2 | read c1 c2
    echo $i $c1 $c2
done > input1-1

for i in $(genrange $xrange) ; do
    echo $i $(seq 1 $i) | ./1-2 | read c1 c2
    echo $i $c1 $c2
done > input1-2

for i in $(genrange $xrange) ; do
    echo $i $(seq 1 $i | tac) | ./1-2 | read c1 c2
    echo $i $c1 $c2
done > input1-3

for i in $(genrange $xrange) ; do
    input=$(cat /dev/urandom | tr -cd "[:digit:]" | fold -w 5 | head -n $i)
    echo $i $input | ./2-2 | read c1 c2
    echo $i $c1 $c2
done > input2-1

for i in $(genrange $xrange) ; do
    echo $i $(seq 1 $i) | ./2-2 | read c1 c2
    echo $i $c1 $c2
done > input2-2

for i in $(genrange $xrange) ; do
    echo $i $(seq 1 $i | tac) | ./2-2 | read c1 c2
    echo $i $c1 $c2
done > input2-3

gnuplot <<EOT
set terminal eps enhanced size 10in, 6in
set output "output.eps"

set xlabel "input length"
set ylabel "count"
set xrange $(genrange-gp $xrange)
plot "input1-1" u 1:2 ti "heapsort, random input, comparison", 2.4*x*log(x)
plot "input1-1" u 1:3 ti "heapsort, random input, substitution", 1.6*x*log(x)
plot "input1-2" u 1:2 ti "heapsort, sorted input, comparison", 2.5*x*log(x)
plot "input1-2" u 1:3 ti "heapsort, sorted input, substitution", 1.7*x*log(x)
plot "input1-3" u 1:2 ti "heapsort, reverse sorted input, comparison", 2.3*x*log(x)
plot "input1-3" u 1:3 ti "heapsort, reverse sorted input, substitution", 1.5*x*log(x)
plot "input2-1" u 1:2 ti "quicksort, random input, comparison", 2.2*x*log(x)
plot "input2-1" u 1:3 ti "quicksort, random input, substitution", 1.2*x*log(x)
plot "input2-2" u 1:2 ti "quicksort, sorted input, comparison", (x**2)/2
plot "input2-2" u 1:3 ti "quicksort, sorted input, substitution", 3*x
plot "input2-3" u 1:2 ti "quicksort, reverse sorted input, comparison", (x**2)/2
plot "input2-3" u 1:3 ti "quicksort, reverse sorted input, substitution", 3*x
EOT
