#!/bin/zsh

gcc -o 2-2 2-2.c

xrange="0,511"

function genrange(){
    echo {$(echo $1 | sed "s/,.*//")..$(echo $1 | sed "s/.*,//")}
}

function genrange-gp(){
    echo -n [
    echo -n $1 | sed "s/,/:/"
    echo ]
}

for i in $(genrange $xrange) ; do
    repeat 2 ; do
        input=$(cat /dev/urandom | tr -cd "[:digit:]" | fold -w 5 | head -n $i)
        (echo $i ; echo -n $input) | ./2-2 | read c1 c2
        echo $i $c1 $c2
    done
done > input2

gnuplot <<EOT
set terminal eps enhanced size 10in, 6in
set output "output2.eps"

set xlabel "input length"
set ylabel "count"
set xrange $(genrange-gp $xrange)
plot "input2" u 1:2 ti "c1", 2.2*x*log(x)
plot "input2" u 1:3 ti "c2", 1.2*x*log(x)
EOT
